spring.application.name=foodresq

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-misty-wave-al8wpjj3.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_2NIcshKERYZ7}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT (Base64-encoded secret >= 32 bytes; OVERRIDE in production via env var)
app.jwt.secret=ZGV2LW9ubHktY2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tcGxlYXNlLXVzZS1hLWxvbmctc2VjcmV0
app.jwt.expiration-ms=86400000